# Configuration globale de Prometheus
  global:
    scrape_interval: 15s
    evaluation_interval: 15s

  # Liste des cibles a scraper
  scrape_configs:
    # Prometheus se scrape lui-meme
    - job_name: "prometheus"
      static_configs:
        - targets: ["localhost:9090"]
    # Node Exporter : metriques systeme
    - job_name: "node-exporter"
      static_configs:
        - targets: ["node-exporter:9100"]